repos:
  - repo: https://github.com/psf/black
    rev: 24.12.1
    hooks:
      - id: black
        language_version: python3.10
        args: ["--line-length=100"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: ["--line-length=100"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests", "types-jinja2"]
        args: ["src", "--python-version=3.11"]
        files: ^src/

ci:
  autofix_commit_msg: "chore(pre-commit): Auto fixes from pre-commit hooks"
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "chore(pre-commit): Auto update hooks"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
